
    let here = document.querySelector('.here');
    let inp = document.querySelector('#inp');
    window.onload=function(){
        inp.focus();
    };

    document.addEventListener('keypress', (keyNum) => {
        if (keyNum.keyCode == 13) {
    pressed();
        } else if (keyNum.key == 'Enter') {
    pressed();
        }
    });

    function pressed() {
        let txtSplit = document.getElementById('inp').value.toUpperCase().split(/[.\s]/g); 
        let text = txtSplit.join('');
        const acr_obj = {
            '' : '...',
            '2FA' : 'Two Factor Authentication',
            '10G' : '10 Galapago Street\n\n This is a former data center.\n Currently houses a few network switches and a defunct mainframe.',
            'A&V' : 'Arts & Venues',
            'AA' : 'Accela Automation',
            'AAD' : 'Azure Active Directory',
            'AB' : 'Arrest Booking | Analytics Bureau',
            'ACA' : 'Accela Citizen Access',
            'ACAMS' : 'Association of Certified Anti-Money Laundering Specialists',
            'ACCC' : 'Arts Complex Communication Center',
            'ACH' : 'Automated Clearing House',
            'ACI' : 'Application Centric Infrastructure',
            'ACL' : 'Access Control Lists',
            'ACP' : 'Accela Civic Platform',
            'ACSES' : 'Automated Child Support Enforcement System',
            'AD' : 'Active Directory',
            'ADA' : 'Americans with Disabilities Act',
            'ADMA' : 'Active Directory Management Agent',
            'ADFS' : 'Active Directory File Service',
            'ADO' : 'Azure DevOps',
            'ADS' : 'Alternate Data Streams',
            'ADUC' : 'Active Directory Users and Computers',
            'AEM' : 'Adobe Experience Manager',
            'AES' : 'Audio Engineers Society | Advanced Encryption Standard',
            'AFAIK' : 'As Far As I Know',
            'AFIS' : 'Automated Fingerprint Identification System',
            'AGOL' : 'ArcGis OnLine',
            'AI' : 'Artificial Intelligence',
            'AID' : 'Assesment Intake and Diversion',
            'AJAX' : 'Asynchronous Javascript And XML',
            'AKA' : 'Also Known As',
            'ANI' : 'Automatic Number Identification',
            'ANT' : 'ActiveNeT',
            'AO' : 'Auditor\'s Office',
            'AOB' : 'Airport Office Building',
            'AP' : 'Accounts Payable',
            'APCD' : 'Air Pollution Control Division',
            'API' : 'Application Programming Interface',
            'APIPA' : 'Automatic Private IP Addressing',
            'APM' : 'Active Payment Manager',
            'APO' : 'Animal Protection Officer',
            'APP' : 'APPlication',
            'ARIES' : 'AutoReturn Integrated Enterprise System',
            'ARP' : 'Address Resolution Protocol',
            'ARPA' : 'American Rescue Plan Act',
            'ARM' : 'Advanced RISC Machine',
            'ASA' : 'Average Speed of Answer',
            'ASCII' : 'American Standard Code for Information Interchange',
            'ASI' : 'Application Specific Information',
            'ASL' : 'American Sign Language',
            'ASP' : 'Application Service Provider',
            'ATA' : 'Advanced Technology Attachment',
            'ATF' : 'Automated Test Framework',
            'ATIMS' : 'Activities Tracking Information Management System',
            'ATM' : 'At The Moment',
            'ATX' : 'Advanced Technology eXtended',
            'AUA' : 'Acceptable Use Agreement',
            'AUD' : 'AUDitor',
            'AV' : 'Audio Visual | Arts & Venues',
            'AVD' : 'Arts & Venues Denver',
            'AWS' : 'Amazon Web Services',
            'BAS' : 'Building Automation System',
            'BAZ' : 'Board of Adjustment for Zoning',
            'BB' : 'Be Back',
            'BBL' : 'Be Back Later',
            'BBM' : 'Buffalo Bill Museum',
            'BCP' : 'Business Continuity Plan',
            'BEM' : 'Block Element Modifier',
            'BI' : 'Business Intelligence',
            'BIA' : 'Business Impact Analysis',
            'BIAS' : 'Business Intelligent Application Solutions',
            'BIOS' : 'Basic Input Output System',
            'BIPOC' : 'Black Indigenous and People Of Color',
            'BMK' : 'BenchMarK',
            'BMO' : 'Budget Management Office',
            'BLDG' : 'BuiLDinG',
            'BOE' : 'Board of Ethics',
            'BOSS' : 'Back Office System Software',
            'BPP' : 'Business Personal Property',
            'BRB' : 'Be Right Back',
            'BRM' : 'Business Relationship Management',
            'BSD' : 'Berkeley Software Distribution',
            'BSOD' : 'Blue Screen Of Death',
            'BTW' : 'By The Way',
            'C&R' : 'Clerk and Recorder',
            'CAB' : 'Change Advisory Board',
            'CAC' : 'Cisco AnyConnect',
            'CAD' : 'Computer Aided Design',
            'CAMA' : 'Computer Assisted Mass Appraisal',
            'CAMEO' : 'Computer Aided Management of Emergency Operations',
            'CAPM' : 'Certified Associate in Project Management',
            'CAO' : 'City Attorney\'s Office',
            'CAPTCHA' : 'Completely Automated Public Turing test to tell Computers and Humans Apart',
            'CART' : 'Communication Access Realtime Translation',
            'CAS' : 'Client Access Settings',
            'CASP' : 'CompTIA Advanced Security Practitioner',
            'CASR' : 'Climate Action, Sustainability & Resiliency',
            'CBH' : 'Community Behavioral Health',
            'CBMS' : 'Colorado Benefits Management System',
            'CC' : 'Creative Cloud',
            'CCAP' : 'Child Care Assistance Program',
            'CCB' : 'City and County Building',
            'CCD' : 'City and County of Denver',
            'CCIC' : 'Colorado Crime Information Center',
            'CCNA' : 'Cisco Certified Network Associate',
            'CCNP' : 'Cisco Certified Network Professional',
            'CORHIO' : 'Colorado Regional Health Information Organization',          
            'CCTC' : 'County Courts Teleconferencing',
            'CD' : 'Compact Disc',
            'CDHS' : 'Colorado Deprtment of Human Services',
            'CDPHE' : 'Colorado Department of Public Health and Environment',
            'CDL' : 'Commercial driver\'s License',
            'CDN' : 'Content Delivery Network',
            'CDOC' : 'Colorado Department Of Corrections',
            'CDOT' : 'Colorado Dept Of Transportation',
            'CDP' : 'Community Development & Planning',
            'CEH' : 'Certified Ethical Hacker',
            'CFP' : 'County Fusion Property',
            'CGAIT' : 'Colorado Government Association of IT',
            'CGIS' : 'Contracting Grants Invoice System',
            'CGSS' : 'Certified Global Sanctions Specialist',
            'CHM' : 'Community Health Management',
            'CHRI' : 'Criminal History Record Information',
            'CI' : 'Configuration Item',
            'CIO' : 'Chief Information Officer',
            'CIP' : 'Capital Improvement Program',
            'CISA' : 'Cybersecurity and Infrastructure Security Agency',
            'CISC' : 'Complex Instruction Set Computer',
            'CISM' : 'Critical Incident Stress Management',
            'CISSP' : 'Certified Information Systems Security Professional',
            'CIT' : 'Computer Information Tool',
            'CJI' : 'Criminal Justice Information',
            'CJIS' : 'Criminal Justice Information Services',
            'CL' : 'Contractor Licensing',
            'CLI' : 'Crime Lab Interface',
            'CLR' : 'CLerk & Recorder',
            'CM' : 'Content Manager',
            'CMDB' : 'Configuration Management Database',
            'CMOS' : 'Complementary Metal Oxide Semiconductor',
            'CMS' : 'Content Management System',
            'CMU' : 'Commision Management Unit',
            'CO' : 'Change Order',
            'COB' : 'Close Of Business',
            'COBRA' : 'Consolidated Omnibus Budget Reconciliation Act',
            'COCT' : 'County Court',
            'COG' : 'Continuity of Government',
            'COJL' : 'COunty JaiL',
            'COMPTIA' : 'COMPuting Technology Industry Association',
            'CON' : 'Contract',
            'COO' : 'Chief Operating Officer',
            'COOP' : 'Continuity Of Operations Plan',
            'CORA' : 'Colorado Open Records Act',
            'CORE' : 'CAMA OASIS Replacement Endeavour',
            'CORRA' : 'Colorado Open Records Request Act',
            'CORS' : 'Cross-Origin Resource Sharing',
            'COTS' : 'Customer Off The shelf',
            'COVID' : 'COrona VIrus Disease',
            'CP' : 'Contingency Plan',
            'CPC' : 'Central Platte Campus',
            'CPD' : 'Community Planning and Development',
            'CPHE' : 'Colorado Public Health Emergency',
            'CPL' : 'Control PaneL',
            'CPR' : 'CardioPulmonary Resuscitation',
            'CPU' : 'Central Processing Unit',
            'CR' : 'Clerk and Recorder',
            'CRB' : 'Conduct Review Bureau',
            'CRM' : 'Customer Relationship Management',
            'CRO' : 'Community Resource Officers',
            'CRP' : 'Community Reentry Project',
            'CRT' : 'Civilian Report Technician | Review Tracking',
            'CRUD' : 'Create Read Update Delete',
            'CS' : 'Career Service',
            'CSA' : 'Career Service Authority',
            'CSB' : 'Career Services Board',
            'CSC' : 'Civil Service Commission',
            'CSDM' : 'Common Service Data Model',
            'CSHO' : 'Career Service Hearing Office',
            'CSM' : 'Customer Service Management',
            'CSP' : 'Cloud Solution Provider',
            'CSR' : 'Customer Service Representative',
            'CSS' : 'Child Support Services | Cascading Style Sheet',
            'CSV' : 'Comma Separated Value',
            'CTO' : 'Chief Technical Officer',
            'CUA' : 'Computer User Agreement',
            'CUWA' : 'Colorado Urban Workforce Alliance',
            'CV' : 'CommVault',
            'CVM' : 'Colorado Volunteer Mobilizer',
            'CW' : 'Child Welfare | Contingent Worker',
            'CYSA' : 'CYberSecurity Analyst',
            'DA' : 'District Attorney',
            'DAM' : 'Denver Art Museum',
            'DAP' : 'Denver Animal Protection',
            'DAS' : 'Denver Animal Shelter',
            'DATA' : 'Denver Area Transportation Access',
            'DAX' : 'Data Analysis eXpressions',
            'DB' : 'DataBase',
            'DBA' : 'DataBase Analyst | DataBAse',
            'DBG' : 'Denver Botanic Gardens',
            'DC' : 'Domain controller',
            'DCC' : 'Denver County Court | Denver City Council',
            'DCH' : 'Denver Children\'s Home',
            'DCO' : 'Data Center Operations',
            'DDC' : 'Denver Detention Center',
            'DDOS' : 'Distributed Denial Of Service',
            'DDPHE' : 'Denver Department of Public Health & Environment',
            'DDR' : 'Double Data Rate',
            'DDS' : 'Data Distribution Service',
            'DEB' : 'Denver Employee Bulletin',
            'DECC' : 'Denver Employees Charitable Campaign',
            'DED' : 'Denver Election Division',
            'DEDO' : 'Denver Economic Development & Opportunity',
            'DEH' : 'Department of Environmental Health',
            'DEI' : 'Diversity Equity Inclusion',
            'DEN' : 'New name for DENver international airport',
            'DERP' : 'Denver Employee Retirement Plan',
            'DEVO' : 'Denver Employees Volunteer Opportunities',
            'DFD' : 'Denver Fire Department',
            'DFIR' : 'Digital Forensics and Incident Response',
            'DHCP' : 'Dynamic Host Configuration Protocol',
            'DHH' : 'Denver Health and Hospitals',
            'DHHA' : 'Denver Health & Hospital Authority',
            'DHMC' : 'Denver Health Medical Center',
            'DHS' : 'Denver of Human Services',
            'DIA' : 'Denver International Airport',
            'DIKW' : 'Data Information Knowledge Wisdom',
            'DIMM' : 'Dual In-line Memory Module',
            'DIMS' : 'Digital Imaging Management System',
            'DISBO' : 'DIvision of Small Business Opportunity',
            'DL' : 'Distribution List',
            'DLL' : 'Dynamic Link Library',
            'DM' : 'Denver Marketing',
            'DMARC' : 'Domain-based Message Authentication, Reporting & Conformance',
            'DMMS' : 'Denver Marketing & Media Services',
            'DMS' : 'DM Marketing Services',
            'DMV' : 'Department of Motor Vehicles',
            'DMZ' : 'Demilitarized Zone',
            'DN' : 'Distinguished Name',
            'DNA' : 'DeoxyriboNucleic Acid',
            'DNN' : 'DotNetNuke',
            'DNS' : 'Domain Name System',
            'DNU' : 'Do Not Use',
            'DNVR' : 'DeNVeR',
            'DOA' : 'Dead On Arrival',
            'DOC' : 'Department Of Corrections',
            'DOF' : 'Department Of Finance',
            'DOLE' : 'Department of Labor & Employment',
            'DOM' : 'Document Object Model',
            'DOMPD' : 'Denver Office of the Municipal Public Defender',
            'DOMV' : 'DOMestic Violence',
            'DOR' : 'Department of Revenue',
            'DORA' : 'Department of Regulatory Agencies',
            'DOHS' : 'Department Of Housing Stability',
            'DOS' : 'Department Of Safety',
            'DOSP' : 'Denver Office of Strategic Partnership',
            'DOT' : 'Department of Transportation',
            'DOTI' : 'Department of Transportation and Infrastructure',
            'DP' : 'Display Port',
            'DPAC' : 'Denver Performing Arts Complex',
            'DPA' : 'Denver Police Academy',
            'DPD' : 'Denver Police Department',
            'DPHE' : 'Department of Public Health & Environment',
            'DPI' : 'Dots Per Inch',
            'DPL' : 'Denver Public Library',
            'DPR' : 'Denver Parks & Recreation',
            'DPS' : 'Denver Public Schools',
            'DR' : 'Disaster Recovery',
            'DRCOG' : 'Denver Regional Council Of Governments',
            'DRE' : 'Department of Real Estate',
            'DRMC' : 'Denver Revised Municipal Code',
            'DRP' : 'Disaster Recovery Plan',
            'DRY' : 'Don\'t Repeat Yourself',
            'DSBO' : 'Denver Small Business Ops',
            'DSD' : 'Denver Sheriff Department',
            'DSF' : 'Denver Scholarship Fund',
            'DSP' : 'DiSPatcher',
            'DSS' : 'Data Security Standards',
            'DTS' : 'DeskTop Support',
            'DTU' : 'Data and Technology Unit',
            'DU' : 'Denver University',
            'DUO' : 'Denver Utilities Online',
            'DV' : 'Domestic Violence',
            'DVD' : 'Digital Video Disc',
            'DVI' : 'Digital Visual Interface',
            'DWD' : 'Division of Workforce Development',
            'E&L' : 'Excise and License',
            'EAC' : 'Employee Advisory Council | Exchange Admin Center',
            'EAM' : 'Enterprise Asset Management system',
            'EAMS' : 'Enterprise Asset Management System',
            'EAP' : 'Employee Assistance Program',
            'EBT' : 'Electronic Benefits Transfer',
            'ECAB' : 'Emergency Change Advisory Board',
            'EC' : 'Electronic Commerce',
            'ECLU' : 'ECourt Liaison Unit',
            'ECS' : 'Enterprise Cashiering System | Elastic Cloud Storage',
            'ECT' : 'Emergency Call Technician',
            'EDI' : 'Equity Diversity and Inclusion',
            'EDR' : 'Endpoint Detection and Response',
            'EE' : 'Employee Engagement',
            'EEB' : 'Electronic Engineering Bureau',
            'EEOE' : 'Equal Employment Opportunity Employer',
            'EF' : 'Essential Function',
            'EFT' : 'Enterprise File Transfer',
            'EID' : 'Employee IDentification',
            'EITS' : 'Early Identification & Intervention Strategy',
            'EITSS' : 'Early Identification & Intervention Strategy System',
            'EL' : 'Excise and License',
            'ELC' : 'ELection Commission',
            'ELP' : 'Emerging Leaders Program',
            'ELT' : 'Executive Leadership Team',
            'EMCF' : 'eMaster Case File',
            'EMPL' : 'EMPLoyee identification',
            'EMS' : 'Electronic Monitoring System | Environmental Management System',
            'EMT' : 'Emergency Medical Technician',
            'ENARSI' : 'ENterprise Advanced Routing and ServIces',
            'ENS' : 'Employee Notification System',
            'EOC' : 'Emergency Operations Center',
            'EOD' : 'End Of Day',
            'EOP' : 'Exchange Online Protection',
            'EOPR' : 'End Of Probation Report',
            'EPA' : 'Environmental Protection Agency',
            'EPO' : 'Exclusive Provider Organization',
            'ER' : 'Economic Resiliency',
            'ERP' : 'Enterprise resource planning',
            'ESRI' : 'Environmental Systems Research Institute',
            'ETIMS' : 'Electronic Ticket Information Management System',
            'EXL' : 'EXcise and Licensing',
            'EXO' : 'EXchange Online',
            'EZLAPP' : 'EZ Links APPlication',
            'EZLINKS' : 'EZLinks Tee Time Software for Golf',
            'FAAD' : 'Family And Adult Development',
            'FAMLI' : 'Family And Medical Leave Insurance',
            'FAQ' : 'Frequently Asked Questions',
            'FAST' : 'Family Advocacy Support Team',
            'FAT' : 'File Allocation Table',
            'FBI' : 'Federal Bureau of Investigations',
            'FCA' : 'Family Care Act',
            'FCD' : 'Federal Continuity Directive',
            'FCR' : 'First Call Resolution',
            'FEMA' : 'Federal Emergency Management Agency',
            'FFMPEG' : 'Fast Forward Moving Picture Experts Group',
            'FIPPS' : 'Fair Information Practice Principles',
            'FIM' : 'File Integrity Monitoring',
            'FIPS' : 'Federal Information Processing Standards',
            'FLR' : 'First Level Response',
            'FM' : 'Financial Management',
            'FMD' : 'Fleet Maintenance Division',
            'FMLA' : 'Family and Medical Leave Act',
            'FPGA' : 'Field-Programmable Gate Array',
            'FPM' : 'Facilities Planning Management',
            'FQDN' : 'Fully Qualified Domain Name',
            'FRT' : 'Facial Recognition Technology',
            'FRVT' : 'Facial Recognition Vendor Test',
            'FSAM' : 'Federation Service of Access Management',
            'FSB' : 'Front Side Bus',
            'FSH' : 'File SHare',
            'FSM' : 'Field Service Management',
            'FTE' : 'Full Time Employee',
            'FTP' : 'File Transfer Protocol',
            'FTW' : 'For The Win',
            'FU' : 'Featured Updates',
            'FWIW' : 'For What Its Worth',
            'GA' : 'General Availability',
            'GAL' : 'Global Address List',
            'GARE' : 'Government Alliance on Race and Equity',
            'GB' : 'GigaByte',
            'GC' : 'Golf Course | Global Catalog',
            'GCC' : 'Government Community Cloud',
            'GG' : 'Good Game',
            'GGCC' : 'General Government Computer Center',
            'GIAC' : 'Global Information Assurance Certification',
            'GIF' : 'Graphics Interchange Format',
            'GIS' : 'Geographic Information System',
            'GIT' : 'Global Information Tracker',
            'GL' : 'General Ledger',
            'GO' : 'General Offence',
            'GOV' : 'Government',
            'GP' : 'Group Policy',
            'GPO' : 'Group Policy Object',
            'GPS' : 'Global Positioning System',
            'GPU' : 'Graphics Processing Unit',
            'GRC' : 'Governance Risk & Compliance',
            'GRITS' : 'Governance Review In Technology Services',
            'GRIT' : 'Governance Review Information Technology',
            'GRP' : 'GRouP',
            'GS' : 'General Services',
            'GSA' : 'General Services Agency',
            'GSEC' : 'GIAC Security Essentials',
            'GUI' : 'Graphical User Interface',
            'GUID' : 'Globally Unique IDentifier',
            'GYP' : 'Generate Your Projects',
            'HA' : 'High Availability',
            'HALO' : 'High Activity Location Observation',
            'HAM' : 'Hardware Asset Management',
            'HCM' : 'Human Capital Management',
            'HCR' : 'Human rights Community Relations',
            'HDD' : 'Hard Disk Drive',
            'HDI' : 'Help Desk Institute',
            'HDHP' : 'High-Deductible Health Plan',
            'HDMI' : 'High-Definition Multimedia Interface',
            'HDSDI' : 'High Definition Serial Digital Interface',
            'HEIC' : 'High EffIciency video Coding',
            'HI' : 'HawaIi',
            'HID' : 'Human IDentity',
            'HIPAA' : 'Health Insurance Portability and Accountability Act',
            'HISET' : 'HIgh School Equivalency Test',
            'HLA' : 'High-Leval Analysis',
            'HMO' : 'Health Maintenance Organization',
            'HOS' : 'HOusing Stability',
            'HOST' : 'HOusing STability',
            'HR' : 'Human Resources',
            'HRBP' : 'Human Resources Business Partner',
            'HRCP' : 'Human Rights Community Partnership',
            'HRM' : 'Human Resource Management',
            'HRSC' : 'Human ReSourCes',
            'HSA' : 'Health Savings Account',
            'HT' : 'HyperThreading',
            'HTML' : 'HyperText Markup Language',
            'HTTP' : 'HyperText Transfer Protocol',
            'HTTPS' : 'HyperText Transfer Protocol Secure',
            'HUD' : 'Housing and Urban Development',
            'HVAC' : 'Heating Ventilation and Air Conditioning',
            'HYPE' : 'Helping Youth Pursue Excellence',
            'IA' : 'Internal Affairs',
            'IANA' : 'Internet Assigned Numbers Authority',
            'IAS' : 'International Accounting Standards',
            'IBM' : 'International Business Machines',
            'IBT' : 'Internal Billing Transfer',
            'ICCID' : 'Integrated Circuit Card Identification Number',
            'ICMP' : 'Internet Control Message Protocol',
            'ID' : 'IDentification',
            'IDE' : 'Integrated Development Environment',
            'ICT' : 'Information and Communications Technology',
            'IDM' : 'IDentity Management',
            'IDOR' : 'Insecure Direct Object References',
            'IDP' : 'Individual Development Plan',
            'IE' : 'Internet Explorer',
            'IF' : 'Intake Filter',
            'IFUND' : 'Innovation Fund',
            'IGC' : 'Information Governance Committee',
            'III' : 'Interstate Identification Index',
            'ILT' : 'Instructor Lead Training',
            'IM' : 'Incident Management',
            'IMAP' : 'Internet Message Access Protocol',
            'IMEI' : 'International Mobile Equipment Identity',
            'IMO' : 'In My Opinion',
            'IMU' : 'Information Management Unit',
            'IMSI' : 'International Mobile Subscriber Identity',
            'INC' : 'INCident',
            'INF' : 'INFrastructure',
            'IOS' : 'internetwork operating system | iphone operating system',
            'IOT' : 'Internet Of Things',
            'IP' : 'Internet Protocol',
            'IPAM' : 'IP Address Management',
            'IPS' : 'Integrated Parking Solutions',
            'IRC' : 'Internet Relay Chat',
            'IS' : 'Information System',
            'ISA' : 'Interconnection Security Agreement',
            'ISACA' : 'Information Systems Audit and Control Association',
            'ISC' : 'IT Security Certifications',
            'ISCP' : 'Information Systems Contingency Plan',
            'ISE' : 'Integrated Scripting Environment',
            'ISO' : 'Information Security Officer',
            'ISP' : 'Internet Service Provider',
            'IT' : 'Information Technology',
            'ITAM' : 'Information Technology Asset Management',
            'ITBM' : 'IT Business Management',
            'ITIL' : 'Information Technology Infrastructure Library',
            'ITF' : 'IT Fundamentals',
            'ITOM' : 'IT Operations Management',
            'ITSM' : 'Information Technology Service Management',
            'IVR' : 'Interactive Voice Response',
            'JCDF' : 'Justice Center Detention Facility',
            'JK' : 'JoKing',
            'JMS' : 'Jail Management System',
            'JPEG' : 'Joint Photographic Experts Group',
            'JPG' : 'Joint Photographic Experts Group',
            'JRE' : 'Java Runtime Environment',
            'JS' : 'JavaScript',
            'JSON' : 'JavaScript Object Notation',
            'JWT' : 'JSON Web Token',
            'KB' : 'Knowledge Base | KiloByte',
            'KM' : 'Knowledge Management',
            'KPI' : 'Key Performance Indicators',
            'KTLO' : 'Keeping The Lights On',
            'KTM' : 'Kofax Transformation Modules',
            'KVM' : 'Keyboard Video Mouse',
            'L&D' : 'Learning and Development',
            'LD' : 'Learning and Development',
            'LAN' : 'Local Area Network',
            'LAPS' : 'Local Administrator Password Solution',
            'LASO' : 'Local Agency Security Officer',
            'LDAP' : 'Lightweight Directory Access Protocol',
            'LEAP' : 'Low-income Energy Assistance Program',
            'LED' : 'Light-Emitting Diode',
            'LEEP' : 'Law Enforcement Enterprise Portal',
            'LEPC' : 'Local Emergency Planning Committee',
            'LFC' : 'Lindsey-Flanigan Courthouse',
            'LIS' : 'Legislative Information System',
            'LLM' : 'Large Language Model',
            'LMK' : 'Let Me Know',
            'LMS' : 'Learning Management System',
            'LOE' : 'Level Of Effort',
            'LOL' : 'Laugh Out Loud',
            'LTE' : 'Long Term Evolution',
            'LTS' : 'Long Term Support',
            'LVM' : 'Locate, View, Map',
            'MAC' : 'Media Access Control',
            'MAM' : 'Mobile Application Management',
            'MAO' : 'Maximum Allowable Outage',
            'MAPI' : 'Messaging Application Programming Interface',
            'MARC' : 'Metro Area Radio Consortium',
            'MB' : 'MegaByte | MotherBoard',
            'MBR' : 'Master Boot Record',
            'MBPS' : 'Megabits per Second',
            'MCT' : 'Mobile Computer Terminal',
            'MCU' : 'Marvel Cinematic Universe',
            'MD' : 'MarkDown',
            'MDF' : 'Mobile Device Form',
            'MDM' : 'Mobile Device Management',
            'MDT' : 'Mobile Data Terminal',
            'MECM' : 'Microsoft Endpoint Configuration Manager',
            'MEF' : 'Mission Essential Function',
            'MEMUG' : 'Modern Enterprise Management User Group',
            'MFA' : 'Multiple Factor Authentication',
            'MGMT' : 'ManaGeMenT',
            'MHBHC' : 'Mile High Behavioral HealthCare',
            'MHFD' : 'Mile High Flood District',
            'MHS' : 'Mental Health Services',
            'MHUW' : 'Mile High United Way',
            'MI' : 'Major Incident',
            'ML' : 'Machine Learning',
            'MMC' : 'ManageMent Console',
            'MO' : 'Mayor\'s Office',
            'MOA' : 'Memorandum of Agreement',
            'MOE' : 'Metro Over Ethernet',
            'MOEC' : 'Mayors Office for Education and Children',
            'MOS' : 'Manager of Safety',
            'MOU' : 'Memorandum of Understanding',
            'MPEG' : 'Moving Picture Experts Group',
            'MPLS' : 'Multiprotocol Label Switching',
            'MRE' : 'Mobile Report Entry',
            'MS' : 'Microsoft',
            'MSA' : 'My Secure Advantage',
            'MSI' : 'MicroSoft Installer',
            'MTD' : 'Maximum Tolerable Downtime',
            'MTTR' : 'Mean Time To Resolution',
            'MVC' : 'Model View Controller',
            'MVD' : 'Motor Vehicles Department',
            'MVU' : 'Mobile Voting Unit',
            'MYR' : 'MaYoR',
            'NAM' : 'Network Analysis Module',
            'NAS' : 'Network Attached Storage',
            'NAT' : 'Network Address Translation',
            'NATOA' : 'The National Association of Telecommunications Officers and Advisors',
            'NCIC' : 'National Crime Information Center',
            'NDC' : 'North Development Corner',
            'NDCCP' : 'North Denver Cornerstone Collaborative Partnership',
            'NECT' : 'Non-Emergency Call Taker',
            'NEFC' : 'New Employee First Call',
            'NEST' : 'Neighborhood Equity & STabilization',
            'NIBRS' : 'National Incidence Based Reporting System',
            'NIC' : 'Network Interface Card',
            'NIST' : 'National Institute of Standards and Technology',
            'NLP' : 'Natural Language Processing',
            'NLU' : 'Natural Language Understanding',
            'NMC' : 'Nasuni Management Console',
            'NOX' : 'Nitrogen OXide',
            'NP' : 'No Problem',
            'NPM' : 'Node Package Manager',
            'NPS' : 'Net Promoter Score',
            'NSP' : 'Network Service Provider',
            'NSFW' : 'Not Safe For Work',
            'NTFS' : 'New Technology File System',
            'NTP' : 'Network Time Protocol',
            'NVME' : 'NonVolatile Memory Express',
            'NWCO' : 'National Western Center Office',
            'OAM' : 'Oracle Access Manager',
            'OASDI' : 'Old-Age Survivors and Disability Insurance',
            'OASIS' : 'Online Appraisal and Statistical Information System',
            'OBHS' : 'Office of Behavioral Health',
            'OBIEE' : 'Oracle Business Intelligence Enterprise Edition',
            'OCA' : 'Office of Childrens Affairs',
            'OCM' : 'Organisational Change Management',
            'OCR' : 'Office of Clerk and Recorder',
            'OD' : 'OneDrive',
            'ODI' : 'Oracle Data Integrator',
            'OE' : 'Open Enrollment',
            'OEC' : 'Office of Education and Children',
            'OED' : 'Office of Economic Development',
            'OEM' : 'Office of Emergency Management | Oracle Enterprise Manager',
            'OEP' : 'Occupant Emergency Plan',
            'OFEP' : 'Office of Financial EmPowerment',
            'OHI' : 'Office of Health Innovation',
            'OHR' : 'Office of Human Resources',
            'OIAM' : 'Oracle Identity and Access Manager',
            'OID' : 'Oracle Internet Directory',
            'OIM' : 'Office of Independent Monitor | Open Information Model',
            'OIT' : 'Office of Information Technology',
            'OLA' : 'Operational Level Agreement',
            'OLED' : 'Organic Light-Emitting Diode',
            'OME' : 'Office of the Medical Examiner',
            'OMPD' : 'Office of Municipal Public Defender',
            'OOBE' : 'Out Of Box Experience',
            'OOO' : 'Out of Office',
            'OOP' : 'Object Oriented Programming',
            'OP' : 'Over Powered',
            'OPC' : 'Overflow Processing Center',
            'OPD' : 'Office of the Public Defender',
            'OPS' : 'OPerationS',
            'ORG' : 'ORGanization',
            'ORI' : 'Originating Agency Identifier',
            'OS' : 'Operating System',
            'OSE' : 'Office of Special Events',
            'OSEI' : 'Office of Social Equity and Innovation',
            'OSI' : 'Open Systems Interconnection',
            'OSN' : 'Officer Serial Number',
            'OU' : 'Organizational Unit',
            'OVD' : 'Oracle Virtual Directory',
            'OWA' : 'Outlook Web Access',
            'OWASP' : 'Open Web Application Security Project',
            'P&R' : 'Parks and Recreation',
            'PAAS' : 'Platform As A Service',
            'PAB' : 'Police Administration Building',
            'PACE' : 'Prosecution And Code Enforcement',
            'PATA' : 'Parallel Advanced Technology Attachment',
            'PCARD' : 'Procurement CARD',
            'PC' : 'Personal Computer',
            'PCB' : 'Printed Circuit Board',
            'PCI' : 'Payment Card Industry | Peripheral Component Interconnect',
            'PCIDSS' : 'Payment Card Industry Data Security Standard',
            'PCIE' : 'Peripheral Component Interconnect Express',
            'PD' : 'Police Districts',
            'PDA' : 'Problematic Data Action',
            'PDF' : 'Portable Document Format',
            'PDO' : 'Public Defenders Office',
            'PEAK' : 'PEAK Performance Academy',
            'PEF' : 'Project Engagement Framework',
            'PEP' : 'Performance Evaluation Program',
            'PEPR' : 'Performance Evaluation Program Review',
            'PERL' : 'Practical Extraction and Report Language',
            'PERMS' : 'PERMitionS',
            'PGA' : 'Pin Grid Array',
            'PHP' : 'Personal Home Page',
            'PIA' : 'Privacy Impact Assessments',
            'PIAD' : 'Performance Improvement and Accountability Division',
            'PII' : 'Personally Identifiable Information',
            'PING' : 'Packet Inter-Network Groper',
            'PIP' : 'Performance Improvement Plan | Package Installer for Python',
            'PKI' : 'Public Key Infrastructure',
            'PL' : 'Procedural Language',
            'PLC' : 'Programmable Logic Controller',
            'PM' : 'Project Manager',
            'PMEF' : 'Primary Mission Essential Function',
            'PMI' : 'Project Management Institute',
            'PMO' : 'Project Management Office',
            'PMP' : 'Project Management Professional',
            'PNG' : 'Portable Network Graphics',
            'PO' : 'Purchase Order | Probation Officer',
            'POC' : 'Point of Contact',
            'POE' : 'Power Over Ethernet',
            'POP' : 'Post Office Protocol',
            'POS' : 'Point of Sale',
            'POST' : 'Power On Self Test',
            'PPAY' : 'Prompt PAY',
            'PPM' : 'Project & Portfolio Management',
            'PPO' : 'Preferred Provider Organization',
            'PREM' : 'PREMises',
            'PRF' : 'Purchase Request Form',
            'PR' : 'Parks and Recreation',
            'PRA' : 'Parks and Recreation Administration',
            'PRG' : 'Parks and Recreation Golf',
            'PRP' : 'Parks and Recreation Parks',
            'PRR' : 'Parks and Recreation Recreation centers',
            'PS' : 'PowerShell',
            'PSK' : 'Personal Security Key',
            'PST' : 'Personal folder file extension (.PST)',
            'PSU' : 'Power Supply Unit',
            'PTG' : 'Pioneer Technology Group',
            'PTO' : 'Paid Time Off',
            'PTS' : 'Pretrial Tracking System',
            'PUR' : 'PURchasing',
            'PVP' : 'Player Vs Player',
            'PW' : 'Public Works',
            'PWD' : 'Print Working Directory',
            'PWI' : 'Person With Information',
            'PWO' : 'Public Works Operations',
            'PWS' : 'Public Works',
            'PXE' : 'Preboot eXecution Environment',
            'Q&A' : 'Question And Answer',
            'QA' : 'Quality Assurance',
            'QI' : 'Quality Improvement',
            'QMA' : 'QMAtic',
            'QOS' : 'Quality of Service',
            'QR' : 'Quick Response',
            'RACF' : 'Resource Access Control Facility',
            'RACI' : 'Responsible Accountable Consulted Informed',
            'RAID' : 'Redundant Array of Independent (or Inexpensive) Disks',
            'RAM' : 'Random Access Memory',
            'RAT' : 'Remote Administration Tool',
            'RBAC' : 'Role Based Access Control',
            'RCA' : 'Root Cause Analysis',
            'RDBMS' : 'Relational DataBase Management System',
            'RDC' : 'Remote Desktop Connection',
            'RDP' : 'Remote Desktop Protocol',
            'RDSMS' : 'Relational Data Stream Management System',
            'REPL' : 'Read Evaluate Print Loop',
            'REPS' : 'Representative Payee System',
            'REQ' : 'Requisition',
            'REST' : 'REpresentational State Transfer',
            'RFA' : 'Request for Approval',
            'RFP' : 'Request for Proposal',
            'RGB' : 'Red Green Blue',
            'RISC' : 'Reduced Instruction Set Computer',
            'RISE' : 'Rebuilding for an Inclusive and Sustainable Economy',
            'RITM' : 'Request Item',
            'RFM' : 'Reduced Functionality Mode',
            'RJ' : 'Registered Jack',
            'RL' : 'Reinforcement Learning',
            'RLA' : 'Risk Limiting Audit',
            'RMF' : 'Risk Management Framework',
            'RMS' : 'Records Management System',
            'RMT' : 'Risk Management',
            'ROFL' : 'Rolling On the Floor Laughing',
            'ROW' : 'Right of Way',
            'ROWE' : 'Right of Way Enforcement',
            'ROWS' : 'Right Of Way Services',
            'RPG' : 'Role Playing Game',
            'RPO' : 'Recovery Point Objective',
            'RPP' : 'Residential Parking Permit',
            'RSJ' : 'Race and Social Justice',
            'RSJ' : 'Race and Social Justice',
            'RTD' : 'Regional Transportation District',
            'RTO' : 'Recovery Time Objective',
            'RTU' : 'Remote Terminal Unit',
            'RTCC' : 'Real Time Crime Center',
            'SAM' : 'Software Asset Management',
            'SAML' : 'Security Assertion Markup Language',
            'SAN' : 'Storage Area Network',
            'SAP' : 'Systems Applications & Products',
            'SARA' : 'Support And Recovery Assistant',
            'SAS' : 'Statistical Analysis System',
            'SATA' : 'Serial Advanced Technology Attachment',
            'SBA' : 'Small Business Administration',
            'SCA' : 'Special Collections and Archives',
            'SCADA' : 'Supervisory Control And Data Acquisition',
            'SCS' : 'Safe City Safety',
            'SCCM' : 'System Center Configuration Manager',
            'SCOM' : 'System Center Operations Manager',
            'SCORE' : 'State COnfidential REporting / REviewing',
            'SCOT' : 'Safe City Office Tool',
            'SCP' : 'Secure Copy Protocol',
            'SD' : 'Service Desk',
            'SDDS' : 'Secure Document Delivery System',
            'SDE' : 'Spatial Database Engine',
            'SDK' : 'Software Development Kit',
            'SDLC' : 'System Development Life Cycle',
            'SDSDI' : 'Standard Definition Serial Digital Interface',
            'SE' : 'Social Equity',
            'SET' : 'Street Enforcement Team',
            'SFTP' : 'Secure File Transfer Protocol',
            'SFTY' : 'SaFTeY',
            'SFW' : 'Safe For Work',
            'SID' : 'Security IDentification',
            'SIM' : 'Subscriber Identity Module',
            'SIEM' : 'Security Information and Event Management',
            'SKMS' : 'Service Knowledge Management System',
            'SLA' : 'Service-Level Agreement',
            'SLO' : 'Service Level Objective',
            'SMART' : 'Self-Monitoring Analysis and Reporting Technology',
            'SME' : 'Subject Matter Expert',
            'SMH' : 'Shaking My Head',
            'SMS' : 'Short Message Service',
            'SMTP' : 'Simple Mail Transfer Protocol',
            'SNAP' : 'Supplemental Nutrition Assistance Program',
            'SNMP' : 'Simple Network Management Protocol',
            'SNOW' : 'Service NOW',
            'SNR' : 'Single Number Reach',
            'SO2' : 'Sulfur diOxide',
            'SOA' : 'Service Oriented Architecture',
            'SOAP' : 'Simple Object Access Protocol',
            'SOC' : 'Security Operations Center',
            'SODIMM' : 'Small Outline Dual In-line Memory Module',
            'SOHO' : 'Small Office Home Office',
            'SOP' : 'Standard Operating Procedure',
            'SP' : 'Special Publication',
            'SPSS' : 'Statistical Package for the Social Sciences',
            'SQL' : 'Structured Query Language',
            'SRA' : 'Strategic Resource Realignment',
            'SRAE' : 'Sustainability & Resiliency Architectural Engineering',
            'SRF' : 'Special Revenue Fund',
            'SRI' : 'SubResource Integrity',
            'SRP' : 'Standard Response Protocol',
            'SSCP' : 'Systems Security Certified Practitioner',
            'SSD' : 'Solid State Drive',
            'SSH' : 'Secure SHell',
            'SSHD' : 'Solid State Hybrid Drive',
            'SSI' : 'Server Side Includes',
            'SSN' : 'Social Security Number',
            'SSO' : 'Single Sign-On',
            'SSPR' : 'Self Service Password Reset',
            'SSRS' : 'SQL Server Reporting Services',
            'ST&E' : 'Security Test and Evaluation',
            'STARS' : 'Service, Teamwork, Accountability, Respect, Safety',
            'STD' : 'Short Term Disability',
            'STE' : 'Security Test and Evaluation',
            'STP' : 'Shielded Twisted Pair',
            'SUN' : 'Substance Use Navigation',
            'SVC' : 'SerViCe',
            'SVR' : 'SerVeR',
            'SW' : 'SoftWare',
            'SWC' : 'SoftWare Center',
            'SWE' : 'SoftWare Engineering',
            'SWM' : 'Solid Waste Management',
            'SYS' : 'SYStem',
            'TA' : 'Talent Acquisition',
            'TAC' : 'Technology Advisory Council | Time and Attendance Change',
            'TANF' : 'Temporary Assistance for Needy Families',
            'TAS' : 'Technology & Admin Support',
            'TASC' : 'Test Assessing Secondary Completion',
            'TB' : 'TeraByte',
            'TBH' : 'To Be Honest',
            'TBP' : 'To Be Published',
            'TCM' : 'TylerCM',
            'TCP' : 'Transmission Control Protocol',
            'TCS' : 'Tax Collection System',
            'TDR' : 'Timeout Detect Recovery',
            'TELNET' : 'TELEtype | TELEcommunication NETwork',
            'TESU' : 'Technical Electronic Support Unit',
            'TFS' : 'Team Foundation Server',
            'TFT' : 'Thin Film Transistor',
            'TFTP' : 'Trivial File Transfer Protocol',
            'TFW' : 'That Feeling When',
            'TIA' : 'Telecommunications Industry Alliance',
            'TID' : 'Terminal IDentification',
            'TIL' : 'Today I Learned',
            'TLDR' : 'Too Long Didn\'t Read',
            'TLS' : 'Transport Layer Security',
            'TMK' : 'To My Knowledge',
            'TMI' : 'Too Much Information',
            'TMU' : 'Technology Mangement Unit',
            'TN' : 'Twisted Nematic',
            'TOTP' : 'Time-based One-Time Password',
            'TPM' : 'Trusted Platform Module',
            'TRS' : 'Tip Ring Sleeve',
            'TS' : 'Technology Services',
            'TT&E' : 'Test, Training, and Exercise',
            'TTE' : 'Test, Training, and Exercise',
            'TTYL' : 'Talk To You Later',
            'TUI' : 'Text User Interface',
            'TY' : 'Thank You',
            'UAC' : 'User Account Control',
            'UASI' : 'Urban Area Security Initiative',
            'UCCX' : 'Unified Contact Center eXpress',
            'UCF' : 'Unified Compliance Framework',
            'UCR' : 'Unified Crime Reporting',
            'UDP' : 'User Datagram Protocol',
            'UEFI' : 'Unified Extensible Firmware Interface',
            'UI' : 'User Interface',
            'UID' : 'User IDentification',
            'UKG' : 'Ultimate Kronos Group',
            'UPN' : 'User Principle Name',
            'UNCC' : 'Utility Notification Center of Colorado',
            'UPS' : 'Uninterruptible Power Supply',
            'URL' : 'Uniform Resource Locator',
            'US&C' : 'Unified Summons & Complaints',
            'USB' : 'Universal Serial Bus',
            'USPS' : 'United State\'s Postal Service',
            'USR' : 'USeR',
            'USS' : 'Unassigned Self-Service',
            'UTF' : 'Unicode Transformation Format',
            'UTP' : 'Unshielded Twisted Pair',
            'UX' : 'User eXperience',
            'VA' : 'Virtual Agent',
            'VAR' : 'Vendor Assessment Review',
            'VAU' : 'Victim Assistance Unit',
            'VCS' : 'Version Control System',
            'VGA' : 'Video Graphics Array',
            'VIDA' : 'Voice, Interoperability, Data, and Access',
            'VIF' : 'Vehicle Impound Facility',
            'VLAN' : 'Virtual Local Area Network',
            'VLC' : 'Video LAN Client',
            'VM' : 'Virtual Machine',
            'VMS' : 'Video Management Software',
            'VOC' : 'Volatile Organic Compounds',
            'VOCS' : 'Volatile Organic CompoundS',
            'VOIP' : 'Voice Over IP',
            'VP' : 'Vice President',
            'VPN' : 'Virtual Private Network',
            'VR' : 'Vulnerbility Response',
            'VRA' : 'Vendor Risk Assessment',
            'VRF' : 'Virtual Routing and Forwarding',
            'VRM' : 'Vendor Risk Management | Voltage Regulator Module',
            'VSA' : 'Virtual Support Agent',
            'VSPC' : 'Voter Service & Polling Centers',
            'VTL' : 'Virtual Tape Library',
            'W3C' : 'World Wide Web Consortium',
            'WAN' : 'Wide Area Network',
            'WAILIT' : 'Where Am I Logged In To',
            'WAP' : 'Wireless Access Point',
            'WATR' : 'WATerway Resilliency',
            'WC' : 'Water Conservancy',
            'WCGW' : 'What Could Go Wrong?',
            'WCMS' : 'Web Content Management System',
            'WD' : 'WorkDay',
            'WEBB' : 'Wellington E. Webb Bldg. 201 W. Colfax',
            'WER' : 'Windows Error Reporting',
            'WFC' : 'WorkForce Central',
            'WFH' : 'Work From Home',
            'WFM' : 'WorkForce Management',
            'WIFI' : 'WIreless FIdelity',
            'WIP' : 'Work In Progress',
            'WISER' : 'Wireless Information System for Emergency Responders',
            'WMB' : 'Webb Municipal Building',
            'WMD' : 'Wastewater Management Division',
            'WMS' : 'Work Management System',
            'WUFB' : 'Windows Update For Business',
            'WW' : 'Waste Water',
            'WWM' : 'Waste Water Management',
            'WWW' : 'World Wide Web',
            'XO' : 'eXecutive Order',
            'XML' : 'eXtensible Markup Language',
            'YARN' : 'Yet Another Resource Negotiator',
            'YOLO' : 'You Only Live Once',
            'YW' : 'You\'re Welcome',
            'ZIF' : 'Zero Insertion Force',
            'ZMA' : 'Zone Multicast Address',
            'ZNIS' : 'Zoning Neighborhood Inspection Services'
        }

        if (acr_obj[text]) {
            here.textContent = acr_obj[text];
            here.innerHTML = acr_obj[text].replace(/\n/g, '<br>');
        } else {
            here.textContent = 'Not in database, Let me know about it!';
        }
        
    }
